### PR TITLE
Master slave

### PR DESCRIPTION
**Pull request by Dareen**

### CODE REVIEW

**Comment by Dareen** [comment]
@qasimkhan @dcrasto plz review/merge
it was tested on gs-dev for redis => note that redis is NOTconsumed in gss through synapse

**Comment by Dareen** [comment]
along with https://github.com/dubizzle/smartstack/pull/35 for the configuration

**Comment by dcrasto** [comment]
Looks good to me. @qasimkhan could you have a look and merge?

**Comment by qasimkhan** [comment]
g2g

**Pull request merged**
